---
# Role to install a simple script to undeploy all instances of an Okapi module
- name: Install prerequisites from apt
  become: yes
  apt: name={{ item }} state=present
  with_items:
    - libjson-xs-perl
    - libjson-perl
    - curl

- name: Set up Okapi home directory
  become: yes
  file: state=directory path={{ okapi_home }}/bin

- name: Copy okapi-undeploy script
  become: yes
  copy: src=okapi-undeploy dest={{ okapi_home}}/bin/okapi-undeploy mode=0755
