---
# Role to pull the Docker image from folioci and deploy into running Okapi

#########
# Setup #
#########

- name: Pull the mod-users Docker image
  become: yes
  become_user: "{{ folio_user }}"
  docker_image: name=folioci/mod-users
  register: mod_users_pull

- name: Set up mod-users home directory
  become: yes
  file: state=directory path={{ mod_users_home }}/bin

- name: Set up mod-users conf directory
  become: yes
  file: state=directory path={{ mod_users_conf }}

- name: Copy module descriptor
  become: yes
  copy: src=ModuleDescriptor.json dest={{ mod_users_conf }}/ModuleDescriptor.json
  register: mod_users_mod_descr_update

- name: Copy deployment descriptor
  become: yes
  template: src=DeploymentDescriptor.json.j2 dest={{ mod_users_conf }}/DeploymentDescriptor.json
  notify:
    - Restart mod-users

- name: Copy mod-users.conf
  become: yes
  template: src=mod-users.conf.j2 dest={{ mod_users_conf }}/mod-users.conf
  notify:
    - Restart mod-users

- name: Copy mod-users.env
  become: yes
  copy: src=mod-users.env dest=/etc/default/mod-users
  notify:
    - Restart mod-users

- name: Copy mod-users.sh
  become: yes
  copy: src=mod-users.sh dest={{ mod_users_home }}/bin/mod-users.sh mode=0755
  notify:
    - Restart mod-users

- name: Copy mod-users.service file
  become: yes
  template: src=mod-users.service.j2 dest=/usr/lib/systemd/system/mod-users.service
  register: mod_users_service_update
  notify:
    - Restart mod-users

- name: systemctl daemon-reload
  become: yes
  command: systemctl daemon-reload
  when: mod_users_service_update.changed

- name: Enable mod-users service
  become: yes
  service: name=mod-users enabled=yes

#########################
# Undeploy if new image #
#########################

- name: Get tenants
  uri:
    url: "{{ okapi_url }}/_/proxy/tenants"
    status_code: 200
  when:
    - mod_users_pull.changed or mod_users_mod_descr_update.changed
  register: tenants

- name: Check tenant mod-user registration
  uri:
    url: "{{ okapi_url }}/_/proxy/tenants/{{ item.id }}/modules/users-module"
    status_code: 200, 404
  when:
    - mod_users_pull.changed or mod_users_mod_descr_update.changed
    - mod_users_deploy_status.status == 200
  with_items: "{{ tenants.json | default([]) }}"
  register: tenant_mod_users

- name: Unregister mod-users module for tenants if image updated
  uri:
    url: "{{ okapi_url }}/_/proxy/tenants/{{ item[0].id }}/modules/users-module"
    method: DELETE
    status_code: 204
  when:
    - mod_users_pull.changed or mod_users_mod_descr_update.changed
    - item[1].status == 200
  with_nested:
    - "{{ tenants.json | default([]) }}"
    - "{{ tenant_mod_users.results | default([]) }}"

- name: Stop mod-users service if image updated
  become: yes
  service: name=mod-users state=stopped
  when:
    - mod_users_pull.changed or mod_users_mod_descr_update.changed

- name: Un-register mod-users if image updated
  uri:
    url: "{{ okapi_url }}/_/proxy/modules/users-module"
    method: DELETE
    status_code: 204, 404
  when: mod_users_pull.changed or mod_users_mod_descr_update.changed
  register: mod_users_unreg
  changed_when: "mod_users_unreg.status == 204"

#################################
# Register and launch mod-users #
#################################

- name: Check mod-users module registration
  uri:
    url: "{{ okapi_url }}/_/proxy/modules/users-module"
    status_code: 200, 404
  register: mod_users_reg_status

- name: Register mod-users module
  uri:
    url: "{{ okapi_url }}/_/proxy/modules"
    method: POST
    body_format: json
    body: "{{ lookup('file', 'ModuleDescriptor.json') }}"
    status_code: 201
  when: mod_users_reg_status.status == 404
  register: mod_users_reg
  changed_when: "mod_users_reg.status == 201"
  notify: Restart mod-users
