---
folio_user: folio
folio_group: folio

folio_apt_repo_url: https://repository.folio.org/packages/ubuntu
folio_apt_key_id: 469A4045
folio_apt_key_url: https://repository.folio.org/packages/debian/folio-apt-archive-key.asc

# there are currently 3 FOLIO repositories - 'testing', 'xenial', and 'focal'
#   testing - includes dev snapshots
#   xenial - releases only, Java 8 based (through Okapi v3.x)
#   focal - releases only, Java 11+ based (Okapi v4.x on)
# Default is to configure just the 'xenial' and 'focal' repos which
# are the most stable.  If you want snapshots, add 'testing' to this list.
#folio_apt_repos:
#  - xenial
#  - focal
folio_apt_repos:
  - focal
