---
# wait a few seconds to make sure modules are spun up
- wait_for: timeout=5

- name: Login as {{ admin_user.username }}
  uri: 
    url: "{{ okapi_url }}/authn/login"
    method: POST
    body_format: json
    headers: 
      X-Okapi-Tenant: "{{ tenant }}"
      Accept: application/json
      Content-Type: application/json
    body: "{ 'username' : '{{ admin_user.username }}', 'password' : '{{ admin_user.password }}' }"
    status_code: 201
  register: tenant_admin_login
  when: auth_required

# Add RM API key
- name: Add RM API customer ID and key
  uri: 
    url: "{{ okapi_url }}/eholdings/configuration"
    method: PUT
    body_format: json
    headers: 
      Authtoken-Refresh-Cache: "true"
      X-Okapi-Tenant: "{{ tenant }}"
      X-Okapi-Token: "{{ tenant_admin_login.x_okapi_token | default('token') }}"
      Accept: application/json
      Content-Type: application/json
    body: '{"data":{"id":"configuration","type":"configurations","attributes":{"apiKey":"{{ rmapi_key }}","customerId":"{{ rmapi_custid }}"}}}'
    status_code: 200,422
  register: mod_kb_ebsco_rmapi
  changed_when: mod_kb_ebsco_rmapi.status == 200

