---
# Authenticate to supertenant if required
- name: include okapi-authenticate role
  include_role:
    name: okapi-authenticate
  when: supertenant_token is not defined

# Role to pull module descriptors from a central repo

# wait a few seconds to make sure okapi is up
- wait_for: timeout=10

- name: Pull module descriptors
  uri:
    url: "{{ okapi_url }}/_/proxy/pull/modules"
    headers:
      headers:
      X-Okapi-Tenant: "supertenant"
      Accept: application/json
      X-Okapi-Token: "{{ supertenant_token | default('') }}"
    body_format: json
    method: POST
    body: "{{ mod_descr_repos }}"
    timeout: "{{ okapi_pull_timeout }}"
  register: okapi_pull
  changed_when: okapi_pull.json is defined and okapi_pull.json
