---
# Authenticate to supertenant if required
- name: include okapi-authenticate role
  include_role:
    name: okapi-authenticate
  when: supertenant_token is not defined

# Role to deploy test modules
- name: Check test module deployment
  uri:
    url: http://localhost:9130/_/proxy/modules/{{ item }}
    headers:
      X-Okapi-Tenant: "supertenant"
      Accept: application/json
    status_code: 200, 404
  with_items:
    - test-basic
    - test-auth
  register: test_deploy_status

- name: Deploy test-basic module
  uri:
    url: http://localhost:9130/_/proxy/modules
    method: POST
    headers:
      X-Okapi-Tenant: "supertenant"
      X-Okapi-Token: "{{ supertenant_token | default('') }}"
      Accept: application/json
      Content-Type: application/json
    body: "{{ lookup('template', 'test-basic.json.j2') | to_json }}"
    status_code: 201
  when: test_deploy_status.results[0].status == 404

- name: Deploy test-auth module
  uri:
    url: http://localhost:9130/_/proxy/modules
    method: POST
    headers:
      X-Okapi-Tenant: "supertenant"
      X-Okapi-Token: "{{ supertenant_token | default('') }}"
      Accept: application/json
      Content-Type: application/json
    body: "{{ lookup('template', 'test-auth.json.j2') | to_json }}"
    status_code: 201
  when: test_deploy_status.results[1].status == 404

- name: Check test module registration
  uri:
    url: http://localhost:9130/_/discovery/modules/{{ item }}
    headers:
      X-Okapi-Tenant: "supertenant"
      Accept: application/json
    status_code: 200, 404
  with_items:
    - test-basic
    - test-auth
  register: test_reg_status

- name: Register test-basic module
  uri:
    url: http://localhost:9130/_/discovery/modules
    method: POST
    headers:
      X-Okapi-Tenant: "supertenant"
      X-Okapi-Token: "{{ supertenant_token | default('') }}"
      Accept: application/json
      Content-Type: application/json
    body: '{ "srvcId" : "test-basic", "nodeId" : "localhost" }'
    status_code: 201
  when: test_reg_status.results[0].status == 404

- name: Register test-auth module
  uri:
    url: http://localhost:9130/_/discovery/modules
    method: POST
    headers:
      X-Okapi-Tenant: "supertenant"
      X-Okapi-Token: "{{ supertenant_token | default('') }}"
      Accept: application/json
      Content-Type: application/json
    body: '{ "srvcId" : "test-auth", "nodeId" : "localhost" }'
    status_code: 201
  when: test_reg_status.results[1].status == 404

- name: Check testlib tenant
  uri:
    url: http://localhost:9130/_/proxy/tenants/testlib
    headers:
      X-Okapi-Tenant: "supertenant"
      Accept: application/json
    status_code: 200, 404
  register: testlib_status

- name: Create testlib tenant
  uri:
    url: http://localhost:9130/_/proxy/tenants
    method: POST
    headers:
      X-Okapi-Tenant: "supertenant"
      X-Okapi-Token: "{{ supertenant_token | default('') }}"
      Accept: application/json
      Content-Type: application/json
    body: '{ "id" : "testlib", "name" : "Test Library", "description" : "Our Own Test Library" }'
    status_code: 201
  when: testlib_status.status == 404

- name: Enable test-basic module for testlib
  uri:
    url: http://localhost:9130/_/proxy/tenants/testlib/modules
    method: POST
    headers:
      X-Okapi-Tenant: "supertenant"
      X-Okapi-Token: "{{ supertenant_token | default('') }}"
      Accept: application/json
      Content-Type: application/json
    body: '{ "id" : "test-basic" }'

- name: Enable test-auth module for testlib
  uri:
    url: http://localhost:9130/_/proxy/tenants/testlib/modules
    method: POST
    headers:
      X-Okapi-Tenant: "supertenant"
      X-Okapi-Token: "{{ supertenant_token | default('') }}"
      Accept: application/json
      Content-Type: application/json
    body: '{ "id" : "test-auth" }'
