---
okapi_port: 9130
okapi_url: "http://{{ ansible_default_ipv4.address }}:{{ okapi_port }}"
okapi_login_url: "{{ okapi_url }}"
superuser_username: super_admin
superuser_password: admin
user_only: false
