---
# Role to enable mod-circulation for the sample tenant and load sample data

# wait a few seconds to make sure modules are spun up
- wait_for: timeout=5

- name: Login as {{ admin_user.username }}
  uri:
    url: "{{ okapi_url }}/authn/login"
    method: POST
    body_format: json
    headers:
      X-Okapi-Tenant: "{{ tenant }}"
      Accept: application/json
    body: "{ 'username' : '{{ admin_user.username }}', 'password' : '{{ admin_user.password }}' }"
    status_code: 201
  register: tenant_admin_login
  when: auth_required

- name: Grant additional permissions to {{ admin_user.username }} (auth by username)
  uri:
    url: "{{ okapi_url }}/perms/users/{{ admin_user.username }}/permissions"
    method: POST
    body_format: json
    headers:
      X-Okapi-Tenant: "{{ tenant }}"
      X-Okapi-Token: "{{ tenant_admin_login.x_okapi_token }}"
      Accept: application/json
    body: '{ "permissionName" : "{{ item }}" }'
    status_code: 200,422
  register: admin_perms
  changed_when: admin_perms.status == 200
  with_items: "{{ circulation_admin_permissions }}"
  when: auth_required and auth_by_username

- name: Grant additional permissions to {{ admin_user.username }} (auth by id)
  uri:
    url: "{{ okapi_url }}/perms/users/{{ admin_user.perms_user_id }}/permissions"
    method: POST
    body_format: json
    headers:
      X-Okapi-Tenant: "{{ tenant }}"
      X-Okapi-Token: "{{ tenant_admin_login.x_okapi_token }}"
      Accept: application/json
    body: '{ "permissionName" : "{{ item }}" }'
    status_code: 200,422
  register: admin_perms
  changed_when: admin_perms.status == 200
  with_items: "{{ circulation_admin_permissions }}"
  when: auth_required and not auth_by_username

- name: Load loan policies
  uri:
    url: "{{ okapi_url }}/loan-policy-storage/loan-policies"
    method: POST
    body_format: json
    headers:
      Authtoken-Refresh-Cache: "true"
      X-Okapi-Tenant: "{{ tenant }}"
      Accept: application/json
      X-Okapi-Token: "{{ tenant_admin_login.x_okapi_token | default('token') }}"
    body: "{{ lookup('file', item) }}"
    status_code: 201, 422, 500
  register: load_loanp
  changed_when: load_loanp.status == 201
  with_fileglob:
    - loan-policies/*.json

- name: Load loan rules
  uri:
    url: "{{ okapi_url }}/loan-rules-storage"
    method: PUT
    body_format: json
    headers:
      X-Okapi-Tenant: "{{ tenant }}"
      Accept: application/json, text/plain
      X-Okapi-Token: "{{ tenant_admin_login.x_okapi_token | default('token') }}"
    body: "{{ lookup('file', item) }}"
    status_code: 204
  register: load_loanr
  changed_when: load_loanr.status == 204
  with_fileglob:
    - loan-rules/use-example-for-everything.json

- name: Get users for loans
  uri:
    url: "{{ okapi_url }}/users?query=active%3D%22true%22%20and%20type%3D%3Dpatron%20sortby%20personal.lastName%20personal.firstName&limit=6"
    headers:
      Accept: application/json
      X-Okapi-Tenant: "{{ tenant }}"
      X-Okapi-Token: "{{ tenant_admin_login.x_okapi_token|default('token') }}"
  register: loan_users


# 422 (or 500?) error means the data are already there
- name: Load loans
  uri:
    url: "{{ okapi_url }}/circulation/loans"
    method: POST
    body_format: json
    headers:
      X-Okapi-Tenant: "{{ tenant }}"
      Accept: application/json
      X-Okapi-Token: "{{ tenant_admin_login.x_okapi_token | default('token') }}"
    body: "{{ lookup('template', item) | to_json }}"
    status_code: 201,422,500
  register: load_loan
  changed_when: load_loan.status == 201
  with_items:
    - loans/bridget-jones-baby-item.json
    - loans/girl-on-the-train-item.json
    - loans/girl-on-the-train-item-3.json
    - loans/girl-on-the-train-item-2.json
    - loans/interesting-times-item.json
    - loans/interesting-times-item-3.json
    - loans/interesting-times-item-2.json
    - loans/nod-item-2.json
    - loans/nod-item.json
    - loans/temeraire-item.json
    - loans/temeraire2-item.json

# 422 error means the data are already there
- name: Load requests
  uri:
    url: "{{ okapi_url }}/request-storage/requests"
    method: POST
    body_format: json
    headers:
      X-Okapi-Tenant: "{{ tenant }}"
      Accept: application/json
      X-Okapi-Token: "{{ tenant_admin_login.x_okapi_token | default('token') }}"
    body: "{{ lookup('template', item) | to_json }}"
    status_code: 201,422,500
  register: load_request
  changed_when: load_request.status == 201
  with_items:
    - requests/bridget-jones-baby.json
    - requests/girl-on-the-train.json
    - requests/interesting-times.json
    - requests/nod.json
  when: load_requests == true
