---
# role to clone and set up stripes-core from GitHub repo

- name: Install prereqs
  become: yes
  apt: name={{ item }} state=present
  with_items:
    - git

- name: Create stripes home directory
  become: yes
  file: path={{ stripes_home }} state=directory

- name: Clone stripes-core repository
  become: yes
  git: repo=https://github.com/folio-org/stripes-core.git dest={{ stripes_home }}/stripes-core
  register: stripes_core_clone
  notify: Restart stripes

# These will always register as changed - need to make idempotent
- name: Move to Node.js 6.X lts
  become: yes
  command: n lts
 
- name: Configure npm registry for stripes-core
  become: yes
  command: npm config set @folio:registry https://repository.folio.org/repository/npm-folioci/
  args:
    chdir: "{{ stripes_home }}/stripes-core"
  when: stripes_core_clone.changed

- name: Install/update packages for stripes-core
  become: yes
  npm: path={{ stripes_home }}/stripes-core
  when: stripes_core_clone.changed

- name: Configure npm registry for sample modules
  become: yes
  command: npm config set @folio-sample-modules:registry https://repository.folio.org/repository/npm-folioci/
  args:
    chdir: "{{ stripes_home }}/stripes-core"
  when: stripes_core_clone.changed

- name: Check status of stripes.config.js
  stat: path={{ stripes_home }}/stripes-core/stripes.config.js follow=yes
  register: stripes_config

- name: Copy stripes.config.js
  become: yes
  copy: src=stripes.config.js dest={{ stripes_home }}/stripes-core/stripes.config.js
  when: stripes_config.stat.isreg is not defined
  notify: Restart stripes

- name: create folio group
  become: yes
  group: name=folio system=yes

- name: create folio user
  become: yes
  user: name=folio system=yes group=folio

- name: Copy stripes.service file
  become: yes
  template: src=stripes.service.j2 dest=/etc/systemd/system/stripes.service
  notify:
    - systemctl daemon-reload
    - Restart stripes

- name: Register stripes with systemd
  become: yes
  service: name=stripes enabled=yes

- name: Check stripes service status
  become: yes
  command: systemctl status stripes
  ignore_errors: yes
  changed_when: no
  register: stripes_status

- name: Notify handler if stripes is down
  debug: msg="Setting stripes to restart"
  when: stripes_status | failed
  changed_when: yes
  notify: Restart stripes
