---
okapi_port: 9130
okapi_url: "http://{{ ansible_default_ipv4.address }}:{{ okapi_port }}"
auth_required: false
auth_by_username: false
top_down_install: false

admin_user: 
  username: diku_admin 
  password: admin 
  perms_user_id: 2408ae64-56ad-4177-9024-1e35fe5d895c

tenant: diku

inventory_admin_permissions:
  - inventory-storage.all
  - inventory.all

inv_storage_3: true
do_mods_larger: false
shelf_locations: false
hierarchical_locations: true
load_class_types: true
load_name_types: true
load_contrib_types: true
load_id_types: true
load_instance_formats: true
load_instance_types: true
load_platforms: true
load_holdings: true
load_service_points: true
