---
# mod-notes-data role
okapi_port: 9130
okapi_url: "http://{{ ansible_default_ipv4.address }}:{{ okapi_port }}"
mod_notes_prefix: mod-notes
auth_required: false
admin_user: { username: diku_admin, password: admin }
mod_notes_permissions:
  - username: diku_admin
    perms_user_id: 2408ae64-56ad-4177-9024-1e35fe5d895c
    permissions:
      - notes.all
auth_by_username: false
