---
okapi_port: 9130
okapi_url: "http://{{ ansible_default_ipv4.address }}:{{ okapi_port }}"
auth_required: true
tenant: diku
admin_user: { username: diku_admin, password: admin }
num_users: 10
load_addresstypes: true
top_down_install: false
mod_users_ref_only: false
