---
# Use a preconfigured github stripes platform
with_github: true
stripes_github_project: https://github.com/folio-org/stripes-demo-platform
platform_remove_lock: false
stripes_github_version: HEAD

# set use_refspec to true if specifying a refspec instead of a branch
from_refspec: false
# if from_refspec is true, specifiy stripes_github_refspec
#stripes_github_refspec: 
#
# Example using refspec and github:
#    
#    stripes_github_refspec: pull/23/head
#    stripes_github_version: pr-23

platform_remove_lock: false

# OR specify stripes configuration here and configure from ansible templates 
stripes_core_version: "latest"
stripes_components_version: "latest"
stripes_modules:
  - { name: "@folio/users", version: "latest" }
  - { name: "@folio/items", version: "latest" }
  - { name: "@folio/scan", version: "latest" }
  - { name: "@folio/trivial", version: "latest" }
  - { name: "@folio/organization", version: "latest" }
  - { name: "@folio/developer", version: "latest" }
  - { name: "@folio/plugin-markdown-editor", version: "latest" }
  - { name: "@folio/plugin-markdown-better", version: "latest" }
  - { name: "@folio/plugin-find-user", version: "latest" }

# disable okapi-console - https://issues.folio.org/browse/STRIPES-264
#  - { name: "@folio/okapi-console", version: "^0.0.1-test" }

# Other relevant vars
stripes_conf_dir: /etc/folio/stripes
stripes_okapi_port: 9130
disable_auth: false
stripes_okapi_url: "http://{{ ansible_default_ipv4.address }}:{{ stripes_okapi_port }}"
# for when the Okapi URL for building is different than for production
stripes_build_okapi_url: "{{ stripes_okapi_url }}"
stripes_tenant: diku
with_sourcemap: true
node_environment:
  NODE_ENV: production
build_webpack: true
build_module_descriptors: true

with_translations: false
webpack_languages: 'en-US,en-GB,da-DK,de-DE,hu-HU'

# Register module descriptors with Okapi, default false
okapi_register_modules: false
# Enable modules for tenant, default false
okapi_enable_modules: false
# Generate strict module descriptors (with requirements), default false
stripes_strict_md: false

# NPM repository settings
folio_npm_base_url: repository.folio.org/repository/
folio_npm_repo: npm-folio

# Use existing stripes platform yarn.lock
use_folio_snapshot: false
folio_snapshot_url: 'http://folio-snapshot-stable.aws.indexdata.com'

#
# Disabled by default
# 
npm_proxy: false
npm_authtoken: ''

# Set to 'true' to generate  stripes-install.json and okapi-install.json files
# for build-module-list
build_install_files: false

## Other build-modules-list related options. Assumes build_install_files is set to 'true'

# Build okapi-install.json with releases only - no snapshots.  Default 'false'
releases_only: false

# Path to stripes module descriptors
md_path: './ModuleDescriptors'

# Do NOT attempt to enable the following modules or non-modules. Defaults.
exclude_mods: 
  - folio_stripes
  - folio_eslint-config-stripes
  - folio_react-intl-safe-html 
  - folio_react-big-calendar

# Additional backend modules to add to okapi-install.json that wouldn't be added
# via Okapi dependency resolution
# e.g 
# other_mods:
#   - mod-codex-inventory
other_mods: []


# 
