
okapi_role: cluster
# 'eth0' is the default ec2 network interface. May be different on other systems
okapi_interface: eth0
okapi_cluster_port: 9001
okapi_cluster_config_file: ""
okapi_port: 9130
okapi_port_start: 9131
okapi_port_end: 9141
okapi_url: "http://{{ ansible_default_ipv4.address }}:{{ okapi_port }}"
okapi_host: "{{ ansible_default_ipv4.address }}"

# change to 'postgres' for postgres backend
okapi_storage: inmemory

pg_host: localhost
pg_port: 5432
pg_admin_user: folio_admin
pg_admin_password: folio_admin
okapidb_user: okapi
okapidb_password: okapi25
okapidb_name: okapi
okapi_dockerurl: http://localhost:4243

okapi_metrics: 0
carbon_host: localhost
carbon_port: 2003

# Edit the following hazelcast variables as appropriate for your site
# either here or at the host or group var level.  These are mostly
# needed for advanced configuration or running Okapi in 'cluster' mode
# on AWS.
# 
# Set 'hazelcast_aws_conf' to 'true' if 'okapi_role' is 'cluster' and
# you are running on ec2 instances
hazelcast_aws_conf: "false"
hazelcast_aws_region: us-east-1
hazelcast_security_group: okapi
hazelcast_aws_access_key: 12345678
hazelcast_aws_secret_key: 12345678
hazelcast_ec2_tag_key: Group
hazelcast_ec2_tag_value: Demo
hazelcast_address: "10.*"
