---
# mod-circulation role
# folio_user needs to be a user with access to Docker
folio_user: folio
mod_circulation_home: /usr/share/folio/mod-circulation
mod_circulation_conf: /etc/folio/mod-circulation
mod_circulation_mod_descriptor: https://raw.githubusercontent.com/folio-org/mod-circulation/master/ModuleDescriptor-1.0.json
mod_circulation_version: latest
okapi_port: 9130
okapi_url: "http://{{ ansible_default_ipv4.address }}:{{ okapi_port }}"
