---
# Role to pull the Docker images from folioci and deploy into running Okapi

#########
# Setup #
#########

- name: Pull the mod-auth Docker images
  become: yes
  become_user: "{{ folio_user }}"
  docker_image: name={{ item.docker_image }}
  register: mod_auth_pull
  with_items: "{{ mod_auth_modules }}"

- name: Set up mod-auth home directory
  become: yes
  file: state=directory path={{ mod_auth_home }}/bin

- name: Set up mod-auth conf directory
  become: yes
  file: state=directory path={{ mod_auth_conf }}

- name: Copy module descriptors to remote
  become: yes
  get_url: url={{ item.mod_descriptor }} dest={{ mod_auth_conf }}/ModuleDescriptor_{{ item.module }}.json
  register: mod_auth_mod_descr_update
  with_items: "{{ mod_auth_modules }}"

- name: Fetch module descriptors from remote
  fetch: src={{ mod_auth_conf }}/ModuleDescriptor_{{ item.module }}.json dest=/tmp
  with_items: "{{ mod_auth_modules }}"

- name: Copy deployment descriptors
  become: yes
  template: src=DeploymentDescriptor_{{ item.module }}.json.j2 dest={{ mod_auth_conf }}/DeploymentDescriptor_{{ item.module }}.json
  with_items: "{{ mod_auth_modules }}"
  notify:
    - Restart mod-auth

- name: Create mod_auth postgresql user
  become: yes
  become_user: postgres
  postgresql_user:
    name: "{{ pg_user }}"
    password: "{{ pg_password }}"
    role_attr_flags: SUPERUSER

- name: Create mod_auth db
  become: yes
  become_user: postgres
  postgresql_db: name={{ mod_auth_db }} owner={{ pg_user }}

- name: Copy mod-auth.conf
  become: yes
  template: src=mod-auth.conf.j2 dest={{ mod_auth_conf }}/mod-auth.conf
  notify:
    - Restart mod-auth

- name: Copy mod-auth.env
  become: yes
  copy: src=mod-auth.env dest=/etc/default/mod-auth
  notify:
    - Restart mod-auth

- name: Copy mod-auth.sh
  become: yes
  copy: src=mod-auth.sh dest={{ mod_auth_home }}/bin/mod-auth.sh mode=0755
  notify:
    - Restart mod-auth

- name: Copy mod-auth.service file
  become: yes
  template: src=mod-auth.service.j2 dest=/etc/systemd/system/mod-auth.service
  register: mod_auth_service_update
  notify:
    - Restart mod-auth

- name: systemctl daemon-reload
  become: yes
  command: systemctl daemon-reload
  when: mod_auth_service_update.changed

- name: Enable mod-auth service
  become: yes
  service: name=mod-auth enabled=yes

##########################
# Undeploy if new images #
##########################

- name: Get tenants
  uri:
    url: "{{ okapi_url }}/_/proxy/tenants"
    status_code: 200
  when:
    - mod_auth_pull.changed or mod_auth_mod_descr_update.changed
  register: tenants

- name: Check tenant mod-user registration
  uri:
    url: "{{ okapi_url }}/_/proxy/tenants/{{ item[0].id }}/modules/{{ item[1].module }}"
    status_code: 200, 404
  when:
    - mod_auth_pull.changed or mod_auth_mod_descr_update.changed
  with_nested:
    - "{{ tenants.json | default([]) }}"
    - "{{ mod_auth_modules }}"
  register: tenant_mod_auth

- name: Unregister mod-auth module for tenants if images updated
  uri:
    url: "{{ okapi_url }}/_/proxy/tenants/{{ item[0].id }}/modules/{{ item[1].json.id }}"
    method: DELETE
    status_code: 204
  when:
    - mod_auth_pull.changed or mod_auth_mod_descr_update.changed
    - item[1].status == 200
  with_nested:
    - "{{ tenants.json | default([]) }}"
    - "{{ tenant_mod_auth.results | default([]) }}"

- name: Stop mod-auth service if image updated
  become: yes
  service: name=mod-auth state=stopped
  when:
    - mod_auth_pull.changed or mod_auth_mod_descr_update.changed

- name: Un-register mod-auth if image updated
  uri:
    url: "{{ okapi_url }}/_/proxy/modules/{{ item.module }}"
    method: DELETE
    status_code: 204, 404
  when: mod_auth_pull.changed or mod_auth_mod_descr_update.changed
  register: mod_auth_unreg
  changed_when: "mod_auth_unreg.status == 204"
  with_items: "{{ mod_auth_modules }}"

####################################
# Register and launch mod-auth #
####################################

- name: Check mod-auth module registration
  uri:
    url: "{{ okapi_url }}/_/proxy/modules/{{ item.module }}"
    status_code: 200, 404
  with_items: "{{ mod_auth_modules }}"
  register: mod_auth_reg_status

- name: Register mod-auth module
  uri:
    url: "{{ okapi_url }}/_/proxy/modules"
    method: POST
    body_format: json
    body: "{{ lookup('file', '/tmp/' ~ inventory_hostname ~ '/' ~ mod_auth_conf ~ '/ModuleDescriptor_' ~ item.module ~ '.json') }}"
    status_code: 201
  when: mod_auth_reg_status.results[item.index].status == 404
  register: mod_auth_reg
  changed_when: "mod_auth_reg.status == 201"
  with_items: "{{ mod_auth_modules }}"
  notify: Restart mod-auth

- meta: flush_handlers
