---
namespace: default
kubeconfig: ~/.kube/config

create_db: false
create_ingress: false
create_rbac: false
# service account that will
# get hazelcast role binding
sa_name: default

app_label: okapi
deployment_name: okapi
ingress_alb_target: none
ingress_name: okapi
ingress_dns: none 

kafka_host: "{{ ansible_default_ipv4.address }}"
kafka_port: 9092

okapi_url: http://okapi:9130
okapidb_user: okapi
okapidb_password: okapi25
okapidb_name: okapi
okapi_docker_repository: folioci
okapi_docker_image: okapi
okapi_docker_tag: latest

hazelcast_version: 3.12

folio_db_user: folio
folio_db_password: folio25
folio_db_database: folio_modules
folio_install_type: kubernetes

pg_host: localhost
pg_maint_db: postgres
pg_port: 5432

service_name: okapi
service_type: ClusterIP
 
