---
namespace: default
kubeconfig: ~/.kube/config

create_db: false
create_ingress: false

app_label: okapi
deployment_name: okapi
ingress_alb_target: none
ingress_name: okapi
ingress_dns: none 

okapi_url: http://okapi:9130
okapidb_user: okapi
okapidb_password: okapi25
okapidb_name: okapi
okapi_docker_repository: folioci
okapi_docker_image: okapi
okapi_docker_tag: latest

hazelcast_version: 3.12

folio_db_user: folio
folio_db_password: folio25
folio_db_database: folio_modules

pg_host: localhost
pg_maint_db: postgres
pg_port: 5432

service_name: okapi
service_type: ClusterIP
