---
# Role to enable mod-users-bl for the sample tenant and load sample data

# wait a few seconds to make sure modules are spun up
- wait_for: timeout=10

- set_fact:
    mod_users_bl_module: "{{ okapi_modules|selectattr('id','match','^'+mod_users_bl_prefix+'(-[0-9].*)?$')|list }}"


- name: Check tenant mod-users-bl registration
  uri:
    url: "{{ okapi_url }}/_/proxy/tenants/diku/modules/{{ mod_users_bl_module.0.id }}"
    status_code: 200, 404
  register: tenant_mod_users_bl

- name: Enable mod-users-bl module for tenant
  uri:
    url: "{{ okapi_url }}/_/proxy/tenants/diku/modules"
    method: POST
    body_format: json
    body: '{ "id" : "{{ mod_users_bl_module.0.id }}" }'
    status_code: 201
  register: mod_users_bl_enable
  changed_when: mod_users_bl_enable.status == 201
  when: tenant_mod_users_bl.status == 404

- name: Assign mod-users-bl permissions to other users (auth by username)
  uri:
    url: "{{ okapi_url }}/perms/users/{{ item.0.username }}/permissions"
    method: POST
    body_format: json
    headers:
      X-Okapi-Tenant: diku
      X-Okapi-Token: "{{ mod_auth_login.x_okapi_token }}"
      Accept: application/json
    body: '{ "permissionName" : "{{ item.1 }}" }'
    status_code: 200,422
  register: mod_users_bl_perms
  changed_when: mod_users_bl_perms.status == 200
  with_subelements:
    - "{{ mod_users_bl_permissions }}"
    - permissions
  when: auth_by_username

- name: Assign mod-users-bl permissions to other users (auth by id)
  uri:
    url: "{{ okapi_url }}/perms/users/{{ item.0.perms_user_id }}/permissions"
    method: POST
    body_format: json
    headers:
      X-Okapi-Tenant: diku
      X-Okapi-Token: "{{ mod_auth_login.x_okapi_token }}"
      Accept: application/json
    body: '{ "permissionName" : "{{ item.1 }}" }'
    status_code: 200,422
  register: mod_users_bl_perms
  changed_when: mod_users_bl_perms.status == 200
  with_subelements:
    - "{{ mod_users_bl_permissions }}"
    - permissions
  when: not auth_by_username
