---
# defaults
okapi_port: 9130
okapi_url: "http://{{ ansible_default_ipv4.address }}:{{ okapi_port }}"
tenant: diku
admin_user:
  username: diku_admin
  password: admin
  first_name: DIKU
  last_name: ADMINISTRATOR
  email: admin@diku.example.org

# supertenant credentials
superuser_username: super_admin
superuser_password: admin
