---
# Create Secret for required connection
- name: create Secret DB Connection
  k8s:
    state: "{{ k8s_state }}"
    definition: "{{ lookup('template', 'db-secrets.yml.j2') }}"
  when: create_secret

- name: get deployed mods
  uri:
    url: "{{ okapi_url }}/_/discovery/modules"
  register: deployed_modules_req

- name: set deployed modules list
  set_fact:
    deployed_modules: "{{ deployed_modules_req.json | json_query('[].srvcId') }}"

# loop over module_list variables to deploy backend module deployment and service
- include_tasks: module.yml
  loop: "{{ folio_modules }}"
  loop_control:
    loop_var: module_item
  when: module_item.deploy is defined and module_item.deploy
